### ISSUE TITLE
How do I control the thickness of the line ?

### ISSUE THREAD

**Issue by kikonejacob** [teralytics/flowmap.gl#137]
Is it possible to control the size of the line?
I'm trying to display flow where weight is not a concern but I still think the lines are too tichk.
Can I change them myself using a custom rule?

**Comment by ilyabo** [comment]
Prior to version 8 you could provide the `maxFlowThickness` prop. In v8 there's no such prop yet, but you can use `FlowLinesLayer` directly which has finer-grained control over the line thickness.

**Comment by kikonejacob** [comment]
Thanks !
I was using v 7 and cannot get the animation to work with it using deck.gl v8.6.7
I switched to v8 and the animation is showing properly but I would like to control the thickness.  

can I also use  AnimatedFlowLinesLayer directly in v8 ?

**Comment by ilyabo** [comment]
> can I also use AnimatedFlowLinesLayer directly in v8 ?

yes, you can
