### ISSUE TITLE
flowmap.gl does not support react 18.2

### ISSUE THREAD

**Issue by yqwang96** [teralytics/flowmap.gl#139]
when I installed flowmap.gl and  run 'npm i flowmap.gl', an error was occured.

npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"0.14.x - 16.x" from flowmap.gl@4.0.0
npm ERR! node_modules/flowmap.gl
npm ERR!   flowmap.gl@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Does flowmap.gl not support higher versions of react16?

**Comment by ilyabo** [comment]
Check out the new version https://github.com/FlowmapBlue/flowmap.gl

**Comment by yqwang96** [comment]
Thank you for your reply and your dedication. I also found this library 'https://github.com/FlowmapBlue/flowmap.gl'.
But, to be honestly, I am a  rookie in this field. I don't kown how to install this library--'https://github.com/FlowmapBlue/flowmap.gl'. Could you give me some advice for the installation of 'https://github.com/FlowmapBlue/flowmap.gl'?

**Comment by ilyabo** [comment]
Check this example:

https://github.com/FlowmapBlue/flowmap.gl/tree/main/examples/react-app

**Comment by yqwang96** [comment]
Thanks. I have fixed this problem. The performance of flowmap.gl is excellent and impresses me deeply.
Thanks again.
